Backport: fix(bedrock): wrap invalid tool input in object (#19018)
This is an automated backport of #16561 to the release-v6.0 branch. FYI
@n1ckoates
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/amazon-bedrock/src/convert-to-bedrock-chat-messages.test.ts
CONFLICT (content): Merge conflict in packages/amazon-bedrock/src/convert-to-bedrock-chat-messages.test.ts
Auto-merging packages/amazon-bedrock/src/convert-to-bedrock-chat-messages.ts
CONFLICT (content): Merge conflict in packages/amazon-bedrock/src/convert-to-bedrock-chat-messages.ts
error: could not apply cf06314e2d... fix(bedrock): wrap invalid tool input in object (#16561)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Kevin Dawkins <kkdawkins@gmail.com>