Backport: Backport: feat(provider/openai): add `gpt-5.3-chat-latest` (#13275)
This is an automated backport of #13272 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging content/docs/02-foundations/02-providers-and-models.mdx
CONFLICT (content): Merge conflict in content/docs/02-foundations/02-providers-and-models.mdx
Auto-merging content/providers/01-ai-sdk-providers/03-openai.mdx
Auto-merging packages/openai/src/chat/openai-chat-options.ts
Auto-merging packages/openai/src/openai-language-model-capabilities.test.ts
Auto-merging packages/openai/src/openai-language-model-capabilities.ts
Auto-merging packages/openai/src/responses/openai-responses-options.ts
CONFLICT (content): Merge conflict in packages/openai/src/responses/openai-responses-options.ts
error: could not apply 023088cd3... Backport: feat(provider/openai): add `gpt-5.3-chat-latest` (#13272)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>