Backport: fix: reuse google auth per provider instance (#14916)
This is an automated backport of #14102 to the release-v6.0 branch. FYI
@heiwen
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/google-vertex/src/anthropic/google-vertex-anthropic-provider-node.test.ts
CONFLICT (content): Merge conflict in packages/google-vertex/src/anthropic/google-vertex-anthropic-provider-node.test.ts
Auto-merging packages/google-vertex/src/anthropic/google-vertex-anthropic-provider-node.ts
Auto-merging packages/google-vertex/src/google-vertex-auth-google-auth-library.ts
CONFLICT (content): Merge conflict in packages/google-vertex/src/google-vertex-auth-google-auth-library.ts
Auto-merging packages/google-vertex/src/google-vertex-provider.test.ts
CONFLICT (content): Merge conflict in packages/google-vertex/src/google-vertex-provider.test.ts
Auto-merging packages/google-vertex/src/google-vertex-provider.ts
CONFLICT (content): Merge conflict in packages/google-vertex/src/google-vertex-provider.ts
Auto-merging packages/google-vertex/src/maas/google-vertex-maas-provider-node.test.ts
Auto-merging packages/google-vertex/src/maas/google-vertex-maas-provider-node.ts
error: could not apply 96d056d69... fix: reuse google auth per provider instance (#14102)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>
Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>