Backport: ci(backport): check for exisitng PRs and use the force (#13260)
This is an automated backport of #13257 to the release-v6.0 branch. FYI
@gr2m
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging .github/workflows/backport.yml
CONFLICT (content): Merge conflict in .github/workflows/backport.yml
error: could not apply fe0eaf380... ci(backport): check for exisitng PRs and use the force (#13257)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Gregor Martynus <39992+gr2m@users.noreply.github.com>