Backport: Fix bedrock ConverseStream undocumented `/delta/stop_sequence` (#11414)
This is an automated backport of #11410 to the release-v5.0 branch. FYI
@gaspar09
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/amazon-bedrock/src/bedrock-chat-language-model.test.ts
CONFLICT (content): Merge conflict in packages/amazon-bedrock/src/bedrock-chat-language-model.test.ts
Auto-merging packages/amazon-bedrock/src/bedrock-chat-language-model.ts
CONFLICT (content): Merge conflict in packages/amazon-bedrock/src/bedrock-chat-language-model.ts
error: could not apply afe9730ab... Fix bedrock ConverseStream undocumented `/delta/stop_sequence` (#11410)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Gaspar Garcia Jr <gaspar@vercel.com>