Backport: Backport: feat(provider/google): add support for service tier parameter (#13918)
This is an automated backport of #13916 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/15-google-generative-ai.mdx
CONFLICT (content): Merge conflict in content/providers/01-ai-sdk-providers/15-google-generative-ai.mdx
CONFLICT (file location): examples/ai-functions/src/generate-text/google/service-tier.ts added in 4e22c2c07 (Backport: feat(provider/google): add support for service tier parameter (#13916)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/service-tier.ts.
CONFLICT (file location): examples/ai-functions/src/stream-text/google/service-tier.ts added in 4e22c2c07 (Backport: feat(provider/google): add support for service tier parameter (#13916)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/service-tier.ts.
CONFLICT (modify/delete): packages/google/src/__snapshots__/google-generative-ai-language-model.test.ts.snap deleted in HEAD and modified in 4e22c2c07 (Backport: feat(provider/google): add support for service tier parameter (#13916)).  Version 4e22c2c07 (Backport: feat(provider/google): add support for service tier parameter (#13916)) of packages/google/src/__snapshots__/google-generative-ai-language-model.test.ts.snap left in tree.
Auto-merging packages/google/src/google-generative-ai-language-model.test.ts
CONFLICT (content): Merge conflict in packages/google/src/google-generative-ai-language-model.test.ts
Auto-merging packages/google/src/google-generative-ai-language-model.ts
CONFLICT (content): Merge conflict in packages/google/src/google-generative-ai-language-model.ts
Auto-merging packages/google/src/google-generative-ai-options.ts
Auto-merging packages/google/src/google-generative-ai-prompt.ts
CONFLICT (content): Merge conflict in packages/google/src/google-generative-ai-prompt.ts
error: could not apply 4e22c2c07... Backport: feat(provider/google): add support for service tier parameter (#13916)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>