Backport: Backport: chore(provider/google): update available models (#14526)
This is an automated backport of #14524 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging packages/google-vertex/src/google-vertex-options.ts
Auto-merging packages/google/src/google-generative-ai-options.ts
CONFLICT (content): Merge conflict in packages/google/src/google-generative-ai-options.ts
CONFLICT (modify/delete): packages/google/src/google-generative-ai-video-settings.ts deleted in HEAD and modified in 71c52e0c0 (Backport: chore(provider/google): update available models (#14524)).  Version 71c52e0c0 (Backport: chore(provider/google): update available models (#14524)) of packages/google/src/google-generative-ai-video-settings.ts left in tree.
error: could not apply 71c52e0c0... Backport: chore(provider/google): update available models (#14524)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>