Backport: feat(ai): introduce experimental callbacks for embed function (#13637)
This is an automated backport of #13478 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/docs/03-ai-sdk-core/65-event-listeners.mdx
Auto-merging packages/ai/src/embed/embed-many.test.ts
Auto-merging packages/ai/src/embed/embed.test.ts
CONFLICT (content): Merge conflict in packages/ai/src/embed/embed.test.ts
Auto-merging packages/ai/src/generate-text/callback-events.ts
error: could not apply ff9ce30b3... feat(ai): introduce experimental callbacks for embed function (#13478)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>