Backport: Backport: feat (provider/anthropic): support passing metadata.user_id (#13785)
This is an automated backport of #13783 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/05-anthropic.mdx
Auto-merging content/providers/01-ai-sdk-providers/08-amazon-bedrock.mdx
Auto-merging content/providers/01-ai-sdk-providers/16-google-vertex.mdx
CONFLICT (file location): examples/ai-functions/src/generate-text/anthropic/metadata.ts added in 05b8ca2b0 (Backport: feat (provider/anthropic): support passing metadata.user_id (#13783)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/metadata.ts.
Auto-merging packages/anthropic/src/anthropic-messages-language-model.test.ts
Auto-merging packages/anthropic/src/anthropic-messages-language-model.ts
Auto-merging packages/anthropic/src/anthropic-messages-options.ts
CONFLICT (content): Merge conflict in packages/anthropic/src/anthropic-messages-options.ts
error: could not apply 05b8ca2b0... Backport: feat (provider/anthropic): support passing metadata.user_id (#13783)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Walter Korman <shaper@vercel.com>