Backport: fix(ai): fix `providerExecuted` tool approvals being passed to language model twice (#14319)
This is an automated backport of #14289 to the release-v6.0 branch. FYI
@felixarntz
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging packages/ai/src/generate-text/generate-text.test.ts
Auto-merging packages/ai/src/generate-text/generate-text.ts
CONFLICT (content): Merge conflict in packages/ai/src/generate-text/generate-text.ts
Auto-merging packages/ai/src/generate-text/stream-text.test.ts
Auto-merging packages/ai/src/generate-text/stream-text.ts
CONFLICT (content): Merge conflict in packages/ai/src/generate-text/stream-text.ts
error: could not apply f37254792... fix(ai): fix `providerExecuted` tool approvals being passed to language model twice (#14289)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Felix Arntz <felix.arntz@vercel.com>