Backport: fix(langchain): prevent polluting global object.prototype (#16085)
This is an automated backport of #16082 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/langchain/src/adapter.ts
Auto-merging packages/langchain/src/types.ts
CONFLICT (content): Merge conflict in packages/langchain/src/types.ts
Auto-merging packages/langchain/src/utils.test.ts
CONFLICT (content): Merge conflict in packages/langchain/src/utils.test.ts
Auto-merging packages/langchain/src/utils.ts
CONFLICT (content): Merge conflict in packages/langchain/src/utils.ts
error: could not apply c1afaed145... fix(langchain): prevent polluting global object.prototype (#16082)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>
Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>