Backport: Backport: feat (provider/google-vertex): add support for maas models (#13947)
This is an automated backport of #13945 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/16-google-vertex.mdx
CONFLICT (file location): examples/ai-functions/src/generate-text/google/vertex-maas-deepseek.ts added in afb68865f (Backport: feat (provider/google-vertex): add support for maas models (#13945)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/vertex-maas-deepseek.ts.
CONFLICT (file location): examples/ai-functions/src/generate-text/google/vertex-maas-kimi.ts added in afb68865f (Backport: feat (provider/google-vertex): add support for maas models (#13945)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/vertex-maas-kimi.ts.
CONFLICT (file location): examples/ai-functions/src/generate-text/google/vertex-maas-qwen.ts added in afb68865f (Backport: feat (provider/google-vertex): add support for maas models (#13945)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/vertex-maas-qwen.ts.
CONFLICT (file location): examples/ai-functions/src/generate-text/google/vertex-maas-tool-call.ts added in afb68865f (Backport: feat (provider/google-vertex): add support for maas models (#13945)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/vertex-maas-tool-call.ts.
CONFLICT (file location): examples/ai-functions/src/stream-text/google/vertex-maas-deepseek.ts added in afb68865f (Backport: feat (provider/google-vertex): add support for maas models (#13945)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/vertex-maas-deepseek.ts.
CONFLICT (file location): examples/ai-functions/src/stream-text/google/vertex-maas-kimi.ts added in afb68865f (Backport: feat (provider/google-vertex): add support for maas models (#13945)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/vertex-maas-kimi.ts.
CONFLICT (file location): examples/ai-functions/src/stream-text/google/vertex-maas-qwen.ts added in afb68865f (Backport: feat (provider/google-vertex): add support for maas models (#13945)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/vertex-maas-qwen.ts.
CONFLICT (file location): examples/ai-functions/src/stream-text/google/vertex-maas-tool-call.ts added in afb68865f (Backport: feat (provider/google-vertex): add support for maas models (#13945)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/vertex-maas-tool-call.ts.
Auto-merging packages/google-vertex/README.md
Auto-merging packages/google-vertex/package.json
Auto-merging packages/google-vertex/tsconfig.json
Auto-merging pnpm-lock.yaml
CONFLICT (content): Merge conflict in pnpm-lock.yaml
error: could not apply afb68865f... Backport: feat (provider/google-vertex): add support for maas models (#13945)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Sylvie Zhang <114536986+sylviezhang37@users.noreply.github.com>