Fix OpenRouter docs' `streamText` example provided (#11367)
`streamText` returns an object with a property `textStream`, which is
the required iterable; the object itself is not iterable.

<!--
Welcome to contributing to AI SDK! We're excited to see your changes.

We suggest you read the following contributing guide we've created
before submitting:

https://github.com/vercel/ai/blob/main/CONTRIBUTING.md
-->

## Background

<!-- Why was this change necessary? -->
When trying to run the example provided for streaming text:
<img width="872" height="518" alt="image"
src="https://github.com/user-attachments/assets/57abd1ea-bbfd-456e-bf16-146f71115280"
/>

An error was produced:

```ts
16 | for await (const chunk of result) {
                      ^
TypeError: undefined is not a function (near '...chunk of result...')
      at /workspaces/bloom/src/index.ts:16:18
```

This was due to the fact that the example provided in the docs assumes
that `streamText` returns a stream itself. This is incorrect; rather,
`streamText` returns an object with many properties, one of which is
`textStream`.

## Summary

<!-- What did you change? -->
Updated the example to use the correct destructured return property from
`streamText` (`textStream`)

## Manual Verification

<!--
For features & bugfixes.
Please explain how you *manually* verified that the change works
end-to-end as expected (excluding automated tests).
Remove the section if it's not needed (e.g. for docs).
-->
Ran the code on the latest version of `ai` with the `textStream`
property used. Verified it was now working as intended.

## Checklist

<!--
Do not edit this list. Leave items unchecked that don't apply. If you
need to track subtasks, create a new "## Tasks" section

Please check if the PR fulfills the following requirements:
-->

- [ ] Tests have been added / updated (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [ ] A _patch_ changeset for relevant packages has been added (for bug
fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)


<!--
## Future Work


Feel free to mention things not covered by this PR that can be done in
future PRs.
Remove the section if it's not needed.
 -->


<!--
## Related Issues

List related issues here, e.g. "Fixes #1234".
Remove the section if it's not needed.
-->

---------

Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>