Backport: docs: update v6 migration guide (#10824)
This is an automated backport of #10664 to the release-v5.0 branch. FYI
@nicoalbanese
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/docs/08-migration-guides/27-migration-guide-6-0.mdx
CONFLICT (content): Merge conflict in content/docs/08-migration-guides/27-migration-guide-6-0.mdx
error: could not apply ac15f0cee... docs: update v6 migration guide (#10664)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Nico Albanese <49612682+nicoalbanese@users.noreply.github.com>
Co-authored-by: nicoalbanese <gcalbanese96@gmail.com>