Backport: docs: refactor agents section around stabilised agent class (#9247)
This is an automated backport of #9245 to the release-v5.0 branch.
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/docs/03-agents/01-overview.mdx
CONFLICT (content): Merge conflict in content/docs/03-agents/01-overview.mdx
Auto-merging content/docs/03-agents/02-building-agents.mdx
error: could not apply 6fd863f86... docs: refactor agents section around stabilised agent class (#9245)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Nico Albanese <49612682+nicoalbanese@users.noreply.github.com>
Co-authored-by: nicoalbanese <gcalbanese96@gmail.com>
Co-authored-by: vercel[bot] <35613825+vercel[bot]@users.noreply.github.com>