chore(mcp): improve developer experience and test portability (#10402)
## Background

Running tests locally failed without some manual setup and wasn’t fully
cross-platform, leading to bad DX.
Additionally, the TypeScript project references were inconsistent — some
dependencies were included while others were missing.

## Summary

### Missing devDependency

To reproduce this problem do:

1. Clone the repo and run `pnpm i`
2. Run `pnpm build:packages`
3. Run `pnpm test` inside of `packages/mcp` => this will result in
`Error: Cannot find module 'vite'`

Solution: 
- **Added Vitest** as a development dependency as tests depend on it.
- **Updated test configuration imports** to align with Vitest usage. Any
ideas why other packages import defineConfig from vite directly?

### Unix folder expected in test

- **Replaced hard-coded `/tmp`** directory in tests with `os.tmpdir()`
for cross-platform compatibility.

### Missing project reference in tsconfig.json

- **Added `provider-utils`** as a TypeScript project reference to
improve editor support. This also aligns with the path strategy in other
packages of this repo.

## Future Work

1. Other packages import `defineConfig` from `vite`. I guess importing
it from `vitest/config` instead would be more appropiate.
2. I suggest using [pnpm catalogs](https://pnpm.io/catalogs) to define
one version for vitest so that not every package uses another version.

---------

Co-authored-by: Gregor Martynus <39992+gr2m@users.noreply.github.com>