Backport: chore(sentry-example) Update SDK and example (#9130)
This is an automated backport of #9103 to the release-v5.0 branch.
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging pnpm-lock.yaml
CONFLICT (content): Merge conflict in pnpm-lock.yaml
error: could not apply de510bc38... chore(sentry-example) Update SDK and example (#9103)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Sergiy Dybskiy <s@serg.tech>
Co-authored-by: Gregor Martynus <39992+gr2m@users.noreply.github.com>