Backport: Backport: feat (provider/gateway): add disallowPromptTraining provider option (#14041)
This is an automated backport of #14039 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/00-ai-gateway.mdx
CONFLICT (directory rename split): Unclear where to rename examples/ai-functions/src/stream-text/nim to; it was renamed to multiple other directories, with no destination getting a majority of the files.
Auto-merging packages/gateway/src/gateway-language-model.test.ts
Auto-merging packages/gateway/src/gateway-provider-options.ts
error: could not apply 85e476d43... Backport: feat (provider/gateway): add disallowPromptTraining provider option (#14039)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Walter Korman <shaper@vercel.com>