Backport: feat(provider/google): add support for gemini-3.1-flash-image-preview (#12885)
This is an automated backport of #12883 to the release-v5.0 branch. FYI
@felixarntz
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/15-google-generative-ai.mdx
CONFLICT (content): Merge conflict in content/providers/01-ai-sdk-providers/15-google-generative-ai.mdx
Auto-merging content/providers/01-ai-sdk-providers/16-google-vertex.mdx
CONFLICT (content): Merge conflict in content/providers/01-ai-sdk-providers/16-google-vertex.mdx
CONFLICT (file location): examples/ai-functions/src/generate-image/google/gemini-3-1-flash-image.ts added in 45f0a7ffd (feat(provider/google): add support for gemini-3.1-flash-image-preview (#12883)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-image/gemini-3-1-flash-image.ts.
CONFLICT (file location): examples/ai-functions/src/generate-text/google/gemini-3-1-flash-image-output.ts added in 45f0a7ffd (feat(provider/google): add support for gemini-3.1-flash-image-preview (#12883)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/gemini-3-1-flash-image-output.ts.
Auto-merging packages/gateway/src/gateway-language-model-settings.ts
Auto-merging packages/google-vertex/src/google-vertex-image-settings.ts
CONFLICT (content): Merge conflict in packages/google-vertex/src/google-vertex-image-settings.ts
Auto-merging packages/google/src/google-generative-ai-image-settings.ts
CONFLICT (content): Merge conflict in packages/google/src/google-generative-ai-image-settings.ts
Auto-merging packages/google/src/google-generative-ai-options.ts
CONFLICT (content): Merge conflict in packages/google/src/google-generative-ai-options.ts
error: could not apply 45f0a7ffd... feat(provider/google): add support for gemini-3.1-flash-image-preview (#12883)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Felix Arntz <felix.arntz@vercel.com>