Backport: fix(anthropic): reorder assistant content b/w client and provider tool use (#16329)
This is an automated backport of #16312 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging examples/ai-e2e-next/agent/anthropic/web-search-agent.ts
CONFLICT (content): Merge conflict in examples/ai-e2e-next/agent/anthropic/web-search-agent.ts
Auto-merging packages/anthropic/src/convert-to-anthropic-messages-prompt.test.ts
Auto-merging packages/anthropic/src/convert-to-anthropic-messages-prompt.ts
error: could not apply 19c5ee243b... fix(anthropic): reorder assistant content b/w client and provider tool use (#16312)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>