Backport: feat(tools-registry): add Nitrosend (#15794)
This is an automated backport of #14992 to the release-v6.0 branch. FYI
@auscaster
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/tools-registry/registry.ts
CONFLICT (content): Merge conflict in content/tools-registry/registry.ts
error: could not apply 6e05a5704... feat(tools-registry): add Nitrosend (#14992)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>
Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>