Backport: fix (provider/moonshotai): include usage when streaming (#12340)
This is an automated backport of #12337 to the release-v5.0 branch. FYI
@shaper
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
CONFLICT (file location): examples/ai-functions/src/generate-text/moonshot-cache.ts added in d999bdf2d (fix (provider/moonshotai): include usage when streaming (#12337)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/moonshot-cache.ts.
CONFLICT (file location): examples/ai-functions/src/stream-text/moonshot-cache.ts added in d999bdf2d (fix (provider/moonshotai): include usage when streaming (#12337)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/moonshot-cache.ts.
Auto-merging packages/moonshotai/src/moonshotai-provider.ts
error: could not apply d999bdf2d... fix (provider/moonshotai): include usage when streaming (#12337)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

Co-authored-by: Walter Korman <shaper@vercel.com>