Backport: Backport: fix(provider/amazon-bedrock): transform bedrock/anthropic error responses to anthropic format (#14007)
This is an automated backport of #13998 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
CONFLICT (file location): examples/ai-functions/src/stream-text/amazon/bedrock-anthropic-unsupported-beta.ts added in 086c3f9c5 (Backport: fix(provider/amazon-bedrock): transform bedrock/anthropic error responses to anthropic format (#13998)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/bedrock-anthropic-unsupported-beta.ts.
error: could not apply 086c3f9c5... Backport: fix(provider/amazon-bedrock): transform bedrock/anthropic error responses to anthropic format (#13998)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Sylvie Zhang <114536986+sylviezhang37@users.noreply.github.com>