Backport: fix(ai): default missing embedding warnings (#15354)
This is an automated backport of #15324 to the release-v6.0 branch. FYI
@Kage18
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/ai/src/embed/embed-many.test.ts
CONFLICT (content): Merge conflict in packages/ai/src/embed/embed-many.test.ts
Auto-merging packages/ai/src/embed/embed-many.ts
CONFLICT (content): Merge conflict in packages/ai/src/embed/embed-many.ts
Auto-merging packages/ai/src/embed/embed.test.ts
CONFLICT (content): Merge conflict in packages/ai/src/embed/embed.test.ts
Auto-merging packages/ai/src/embed/embed.ts
CONFLICT (content): Merge conflict in packages/ai/src/embed/embed.ts
error: could not apply e3a04191f... fix(ai): default missing embedding warnings (#15324)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>
Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>