Backport: feat(moonshotai): support structured outputs for kimi k2.5 (#16478)
This is an automated backport of #16472 to the release-v6.0 branch. FYI
@n1ckoates
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/31-moonshotai.mdx
Auto-merging packages/moonshotai/src/moonshotai-provider.test.ts
CONFLICT (content): Merge conflict in packages/moonshotai/src/moonshotai-provider.test.ts
Auto-merging packages/moonshotai/src/moonshotai-provider.ts
CONFLICT (content): Merge conflict in packages/moonshotai/src/moonshotai-provider.ts
error: could not apply 5cb600b074... feat(moonshotai): support structured outputs for kimi k2.5 (#16472)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Nick Oates <nick.oates@vercel.com>