Backport: feat(provider/gateway): Server-side image request splitting (#10510)
This is an automated backport of #10506 to the release-v5.0 branch. FYI
@R-Taneja
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/gateway/src/gateway-image-model-settings.ts
Auto-merging packages/gateway/src/gateway-image-model.test.ts
CONFLICT (content): Merge conflict in packages/gateway/src/gateway-image-model.test.ts
Auto-merging packages/gateway/src/gateway-image-model.ts
CONFLICT (content): Merge conflict in packages/gateway/src/gateway-image-model.ts
error: could not apply e8694aff4... feat(provider/gateway): Server-side image request splitting (#10506)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Rohan Taneja <47066511+R-Taneja@users.noreply.github.com>