Backport: fix(openai): allow open_page action type url to be nullish (#10835)
This is an automated backport of #10646 to the release-v5.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
CONFLICT (modify/delete): examples/next-openai/components/tool/azure-web-search-preview-view.tsx deleted in HEAD and modified in b60d2e266 (fix(openai): allow open_page action type url to be nullish (#10646)).  Version b60d2e266 (fix(openai): allow open_page action type url to be nullish (#10646)) of examples/next-openai/components/tool/azure-web-search-preview-view.tsx left in tree.
Auto-merging packages/openai/src/responses/openai-responses-api.ts
Auto-merging packages/openai/src/tool/web-search-preview.ts
CONFLICT (content): Merge conflict in packages/openai/src/tool/web-search-preview.ts
Auto-merging packages/openai/src/tool/web-search.ts
CONFLICT (content): Merge conflict in packages/openai/src/tool/web-search.ts
error: could not apply b60d2e266... fix(openai): allow open_page action type url to be nullish (#10646)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>