Backport: feat(provider/anthropic): add support for new Claude Sonnet 4.6 model (#12648)
This is an automated backport of #12645 to the release-v5.0 branch. Conflicts fixed by @felixarntz

### `git cherry-pick` output

```
Auto-merging content/docs/02-foundations/02-providers-and-models.mdx
Auto-merging content/providers/01-ai-sdk-providers/05-anthropic.mdx
CONFLICT (content): Merge conflict in content/providers/01-ai-sdk-providers/05-anthropic.mdx
Auto-merging content/providers/01-ai-sdk-providers/index.mdx
Auto-merging examples/ai-core/src/generate-text/anthropic-reasoning.ts
Auto-merging examples/ai-core/src/stream-text/anthropic-context-management-clear-tool-uses.ts
Auto-merging examples/ai-core/src/stream-text/anthropic-reasoning.ts
CONFLICT (modify/delete): examples/ai-functions/src/generate-text/anthropic-context-management.ts deleted in HEAD and modified in 2a1c6642b (feat(provider/anthropic): add support for new Claude Sonnet 4.6 model (#12645)).  Version 2a1c6642b (feat(provider/anthropic): add support for new Claude Sonnet 4.6 model (#12645)) of examples/ai-functions/src/generate-text/anthropic-context-management.ts left in tree.
Auto-merging packages/anthropic/src/anthropic-messages-language-model.ts
Auto-merging packages/anthropic/src/anthropic-messages-options.ts
Auto-merging packages/gateway/src/gateway-language-model-settings.ts
error: could not apply 2a1c6642b... feat(provider/anthropic): add support for new Claude Sonnet 4.6 model (#12645)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Felix Arntz <felix.arntz@vercel.com>