Backport: feat(provider/openai): add `gpt-5.3-codex` (#12815)
This is an automated backport of #12814 to the release-v5.0 branch. FYI
@felixarntz
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
CONFLICT (modify/delete): content/providers/03-community-providers/13-codex-cli.mdx deleted in HEAD and modified in 0c9395b15 (feat(provider/openai): add `gpt-5.3-codex` (#12814)).  Version 0c9395b15 (feat(provider/openai): add `gpt-5.3-codex` (#12814)) of content/providers/03-community-providers/13-codex-cli.mdx left in tree.
CONFLICT (modify/delete): content/providers/03-community-providers/46-codex-app-server.mdx deleted in HEAD and modified in 0c9395b15 (feat(provider/openai): add `gpt-5.3-codex` (#12814)).  Version 0c9395b15 (feat(provider/openai): add `gpt-5.3-codex` (#12814)) of content/providers/03-community-providers/46-codex-app-server.mdx left in tree.
Auto-merging packages/gateway/src/gateway-language-model-settings.ts
Auto-merging packages/openai/src/responses/openai-responses-options.ts
error: could not apply 0c9395b15... feat(provider/openai): add `gpt-5.3-codex` (#12814)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Felix Arntz <felix.arntz@vercel.com>