Backport: feat(prodia): add LanguageModel and VideoModel support (#13597)
This is an automated backport of #13364 to the release-v6.0 branch. FYI
@montyanderson
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging packages/prodia/src/prodia-image-model.ts
CONFLICT (content): Merge conflict in packages/prodia/src/prodia-image-model.ts
Auto-merging packages/prodia/src/prodia-provider.test.ts
Auto-merging packages/prodia/src/prodia-provider.ts
CONFLICT (content): Merge conflict in packages/prodia/src/prodia-provider.ts
error: could not apply e2bdcd67b... feat(prodia): add LanguageModel and VideoModel support (#13364)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: monty anderson <work@montyanderson.net>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>