Backport: feat(mcp): deprecate name and use clientName for MCPClient (#15003)
This is an automated backport of #14966 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/docs/07-reference/01-ai-sdk-core/23-create-mcp-client.mdx
Auto-merging examples/ai-e2e-next/app/chat/mcp/chat/route.ts
Auto-merging examples/ai-e2e-next/app/chat/mcp/page.tsx
CONFLICT (content): Merge conflict in examples/ai-e2e-next/app/chat/mcp/page.tsx
Auto-merging packages/ai/src/generate-text/parse-tool-call.test.ts
Auto-merging packages/mcp/src/tool/mcp-client.test.ts
CONFLICT (content): Merge conflict in packages/mcp/src/tool/mcp-client.test.ts
Auto-merging packages/mcp/src/tool/mcp-client.ts
error: could not apply 14517599a... feat(mcp): deprecate name and use clientName for MCPClient (#14966)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>
Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>