Backport: Backport: fix(provider/amazon-bedrock): fix Anthropic reasoning behavior related to Opus 4.7 (#14604)
This is an automated backport of #14602 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging examples/ai-core/src/generate-text/anthropic-xhigh-effort.ts
CONFLICT (file location): examples/ai-functions/src/generate-text/amazon/bedrock-anthropic-reasoning.ts added in fd0f09713 (Backport: fix(provider/amazon-bedrock): fix Anthropic reasoning behavior related to Opus 4.7 (#14602)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/bedrock-anthropic-reasoning.ts.
Auto-merging examples/ai-core/src/stream-text/anthropic-xhigh-effort.ts
CONFLICT (file location): examples/ai-functions/src/stream-text/amazon/bedrock-anthropic-reasoning-ui-stream.ts added in fd0f09713 (Backport: fix(provider/amazon-bedrock): fix Anthropic reasoning behavior related to Opus 4.7 (#14602)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/bedrock-anthropic-reasoning-ui-stream.ts.
CONFLICT (file location): examples/ai-functions/src/stream-text/amazon/bedrock-anthropic-reasoning.ts added in fd0f09713 (Backport: fix(provider/amazon-bedrock): fix Anthropic reasoning behavior related to Opus 4.7 (#14602)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/bedrock-anthropic-reasoning.ts.
Auto-merging packages/amazon-bedrock/src/bedrock-chat-language-model.test.ts
CONFLICT (content): Merge conflict in packages/amazon-bedrock/src/bedrock-chat-language-model.test.ts
Auto-merging packages/amazon-bedrock/src/bedrock-chat-language-model.ts
CONFLICT (content): Merge conflict in packages/amazon-bedrock/src/bedrock-chat-language-model.ts
Auto-merging packages/amazon-bedrock/src/bedrock-chat-options.ts
error: could not apply fd0f09713... Backport: fix(provider/amazon-bedrock): fix Anthropic reasoning behavior related to Opus 4.7 (#14602)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>