Backport: Backport: fix(provider/google): fix Gemini service tier enum after upstream update (#14093)
This is an automated backport of #14091 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/15-google-generative-ai.mdx
Auto-merging examples/ai-core/src/generate-text/google-service-tier.ts
CONFLICT (content): Merge conflict in examples/ai-core/src/generate-text/google-service-tier.ts
Auto-merging examples/ai-core/src/stream-text/google-service-tier.ts
CONFLICT (content): Merge conflict in examples/ai-core/src/stream-text/google-service-tier.ts
Auto-merging packages/google/src/google-generative-ai-language-model.test.ts
Auto-merging packages/google/src/google-generative-ai-options.ts
error: could not apply 0f2b2f11f... Backport: fix(provider/google): fix Gemini service tier enum after upstream update (#14091)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>