Backport: Backport: feat (provider/gateway): add spend reporting support (#13861)
This is an automated backport of #13859 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/00-ai-gateway.mdx
Auto-merging packages/gateway/src/gateway-provider.test.ts
Auto-merging packages/gateway/src/gateway-provider.ts
CONFLICT (content): Merge conflict in packages/gateway/src/gateway-provider.ts
Auto-merging packages/gateway/src/index.ts
error: could not apply 95fedf020... Backport: feat (provider/gateway): add spend reporting support (#13859)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Walter Korman <shaper@vercel.com>