Backport: feat(provider/google): support combining built-in tools with function calling on Gemini 3 (#13993)
This is an automated backport of #13920 to the release-v6.0 branch. FYI
@edwardwc
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging packages/google/src/convert-to-google-generative-ai-messages.test.ts
Auto-merging packages/google/src/convert-to-google-generative-ai-messages.ts
Auto-merging packages/google/src/google-generative-ai-language-model.test.ts
Auto-merging packages/google/src/google-generative-ai-language-model.ts
CONFLICT (content): Merge conflict in packages/google/src/google-generative-ai-language-model.ts
Auto-merging packages/google/src/google-prepare-tools.test.ts
Auto-merging packages/google/src/google-prepare-tools.ts
error: could not apply 01fa606a9... feat(provider/google): support combining built-in tools with function calling on Gemini 3 (#13920)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: edwardwc <edwardwc@protonmail.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>