fix (providers/gateway): fix timestamp error when streaming objects (#6906)
## Background

Using `streamObject` with the gateway provider throws an exception like the below at the end:

```
TypeError: fullResponse.timestamp.toISOString is not a function
    at Object.flush (/Users/shaper/workspace/ai/packages/ai/core/generate-object/stream-object.ts:760:50)
```

This is due to the `Date` object in the `response-metadata` chunk getting serialized to a string over the wire.

## Summary

Look for and rehydrate the stream part's timestamp field into a `Date` object.

## Verification

Ran example script.

## Tasks

- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug fixes / features - run `pnpm changeset` in the project root)
- [x] Formatting issues have been fixed (run `pnpm prettier-fix` in the project root)

## Future Work

Review the v2 language model spec for other similar cases where we may have missed lossy object types like `Date` and `URL`.