Backport: fix(openai): skip passing reasoning items when using previous response id (#15508)
This is an automated backport of #15503 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/openai/src/responses/convert-to-openai-responses-input.test.ts
CONFLICT (content): Merge conflict in packages/openai/src/responses/convert-to-openai-responses-input.test.ts
Auto-merging packages/openai/src/responses/convert-to-openai-responses-input.ts
Auto-merging packages/openai/src/responses/openai-responses-language-model.test.ts
Auto-merging packages/openai/src/responses/openai-responses-language-model.ts
error: could not apply 17b559733... fix(openai): skip passing reasoning items when using previous response id (#15503)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>