Backport: fix(provider/anthropic): minor follow up to support no-op speed standard (#12587)
This is an automated backport of #12582 to the release-v5.0 branch. FYI
@felixarntz
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/05-anthropic.mdx
CONFLICT (content): Merge conflict in content/providers/01-ai-sdk-providers/05-anthropic.mdx
Auto-merging packages/anthropic/src/anthropic-messages-api.ts
Auto-merging packages/anthropic/src/anthropic-messages-language-model.test.ts
Auto-merging packages/anthropic/src/anthropic-messages-language-model.ts
Auto-merging packages/anthropic/src/anthropic-messages-options.ts
error: could not apply 23ac4a301... fix(provider/anthropic): minor follow up to support no-op speed standard (#12582)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Felix Arntz <felix.arntz@vercel.com>