Backport: fix(bedrock): skip passing unsigned reasoning content (#15182)
This is an automated backport of #15181 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/amazon-bedrock/src/convert-to-bedrock-chat-messages.test.ts
CONFLICT (content): Merge conflict in packages/amazon-bedrock/src/convert-to-bedrock-chat-messages.test.ts
Auto-merging packages/amazon-bedrock/src/convert-to-bedrock-chat-messages.ts
CONFLICT (content): Merge conflict in packages/amazon-bedrock/src/convert-to-bedrock-chat-messages.ts
error: could not apply bcbaae644... fix(bedrock): skip passing unsigned reasoning content (#15181)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>