Backport: chore(provider/gateway): update gateway model settings files (#11929)
This is an automated backport of #11925 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/gateway/src/gateway-language-model-settings.ts
CONFLICT (content): Merge conflict in packages/gateway/src/gateway-language-model-settings.ts
error: could not apply 7af4eb4cf... chore(provider/gateway): update gateway model settings files (#11925)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Sylvie Zhang <114536986+sylviezhang37@users.noreply.github.com>