Backport: feat(openai): add new tool search tool (#13534)
This is an automated backport of #13157 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/openai/src/responses/convert-to-openai-responses-input.ts
Auto-merging packages/openai/src/responses/openai-responses-language-model.test.ts
CONFLICT (content): Merge conflict in packages/openai/src/responses/openai-responses-language-model.test.ts
Auto-merging packages/openai/src/responses/openai-responses-language-model.ts
Auto-merging packages/openai/src/responses/openai-responses-prepare-tools.ts
error: could not apply 156cdf060... feat(openai): add new tool search tool (#13157)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>