Backport: Backport: fix(google): fix `serviceTier` to be correctly formatted for Vertex API (#14399)
This is an automated backport of #14397 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
CONFLICT (file location): examples/ai-functions/src/generate-text/google/vertex-service-tier.ts added in 1e1a5ab49 (Backport: fix(google): fix `serviceTier` to be correctly formatted for Vertex API (#14397)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/vertex-service-tier.ts.
CONFLICT (file location): examples/ai-functions/src/stream-text/google/vertex-service-tier.ts added in 1e1a5ab49 (Backport: fix(google): fix `serviceTier` to be correctly formatted for Vertex API (#14397)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/vertex-service-tier.ts.
Auto-merging packages/google/src/google-generative-ai-language-model.test.ts
Auto-merging packages/google/src/google-generative-ai-language-model.ts
CONFLICT (content): Merge conflict in packages/google/src/google-generative-ai-language-model.ts
Auto-merging packages/google/src/google-generative-ai-options.ts
error: could not apply 1e1a5ab49... Backport: fix(google): fix `serviceTier` to be correctly formatted for Vertex API (#14397)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>