Backport: fix: update gemini 3 model id (#10341)
This is an automated backport of #10339 to the release-v5.0 branch. FYI
@nicoalbanese
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/15-google-generative-ai.mdx
CONFLICT (content): Merge conflict in content/providers/01-ai-sdk-providers/15-google-generative-ai.mdx
Auto-merging examples/ai-core/src/generate-text/google.ts
CONFLICT (content): Merge conflict in examples/ai-core/src/generate-text/google.ts
Auto-merging packages/google/src/google-generative-ai-options.ts
CONFLICT (content): Merge conflict in packages/google/src/google-generative-ai-options.ts
error: could not apply 599a97f5b... fix: update gemini 3 model id (#10339)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Nico Albanese <49612682+nicoalbanese@users.noreply.github.com>
Co-authored-by: nicoalbanese <gcalbanese96@gmail.com>