Backport: feat(provider/google): add support for new Google image model aspect ratios and sizes (#12898)
This is an automated backport of #12897 to the release-v5.0 branch. FYI
@felixarntz
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
CONFLICT (modify/delete): examples/ai-functions/src/generate-image/google/gemini-3-1-flash-image.ts deleted in HEAD and modified in 1ece97a41 (feat(provider/google): add support for new Google image model aspect ratios and sizes (#12897)).  Version 1ece97a41 (feat(provider/google): add support for new Google image model aspect ratios and sizes (#12897)) of examples/ai-functions/src/generate-image/google/gemini-3-1-flash-image.ts left in tree.
Auto-merging packages/google/src/google-generative-ai-options.ts
error: could not apply 1ece97a41... feat(provider/google): add support for new Google image model aspect ratios and sizes (#12897)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Felix Arntz <felix.arntz@vercel.com>