Backport: Update Cerebras Models (#9277)
This is an automated backport of #9258 to the release-v5.0 branch.
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/cerebras/CHANGELOG.md
CONFLICT (content): Merge conflict in packages/cerebras/CHANGELOG.md
Auto-merging packages/cerebras/package.json
CONFLICT (content): Merge conflict in packages/cerebras/package.json
error: could not apply 42e9f6401... Update Cerebras Models (#9258)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Kevin Taylor <kevin.taylor@cerebras.net>
Co-authored-by: Gregor Martynus <39992+gr2m@users.noreply.github.com>