Backport: fix(openai): change web search tool action to be optional (#12785)
This is an automated backport of #12706 to the release-v5.0 branch. FYI
@kkawamu1
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/openai/src/responses/__snapshots__/openai-responses-language-model.test.ts.snap
CONFLICT (content): Merge conflict in packages/openai/src/responses/__snapshots__/openai-responses-language-model.test.ts.snap
Auto-merging packages/openai/src/responses/openai-responses-api.ts
Auto-merging packages/openai/src/responses/openai-responses-language-model.test.ts
CONFLICT (content): Merge conflict in packages/openai/src/responses/openai-responses-language-model.test.ts
Auto-merging packages/openai/src/responses/openai-responses-language-model.ts
CONFLICT (content): Merge conflict in packages/openai/src/responses/openai-responses-language-model.ts
Auto-merging packages/openai/src/tool/web-search-preview.ts
CONFLICT (content): Merge conflict in packages/openai/src/tool/web-search-preview.ts
Auto-merging packages/openai/src/tool/web-search.ts
CONFLICT (content): Merge conflict in packages/openai/src/tool/web-search.ts
error: could not apply d5f731234... fix(openai): change web search tool action to be optional (#12706)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: kkawamu1 <58097201+kkawamu1@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>