Backport: feat(openai): add namespaces for tool definitions (#15910)
This is an automated backport of #15904 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/03-openai.mdx
Auto-merging packages/openai/src/responses/openai-responses-api.ts
Auto-merging packages/openai/src/responses/openai-responses-prepare-tools.test.ts
Auto-merging packages/openai/src/responses/openai-responses-prepare-tools.ts
CONFLICT (content): Merge conflict in packages/openai/src/responses/openai-responses-prepare-tools.ts
error: could not apply 6a5800ef0... feat(openai): add namespaces for tool definitions (#15904)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>