Backport: fix(provider/google): support `functionCall.id` when returned by Gemini API and provide matching `functionResponse.id` (#15318)
This is an automated backport of #15317 to the release-v6.0 branch. FYI
@felixarntz
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging packages/google/src/convert-to-google-generative-ai-messages.test.ts
Auto-merging packages/google/src/convert-to-google-generative-ai-messages.ts
CONFLICT (content): Merge conflict in packages/google/src/convert-to-google-generative-ai-messages.ts
Auto-merging packages/google/src/google-generative-ai-language-model.ts
CONFLICT (modify/delete): packages/google/src/google-prompt.ts deleted in HEAD and modified in 41da50cbc (fix(provider/google): support `functionCall.id` when returned by Gemini API and provide matching `functionResponse.id` (#15317)).  Version 41da50cbc (fix(provider/google): support `functionCall.id` when returned by Gemini API and provide matching `functionResponse.id` (#15317)) of packages/google/src/google-prompt.ts left in tree.
error: could not apply 41da50cbc... fix(provider/google): support `functionCall.id` when returned by Gemini API and provide matching `functionResponse.id` (#15317)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>