Backport: fix(provider/amazon-bedrock): fix Anthropic reasoning behavior related to Opus 4.7 (#14602)
This is an automated backport of #14582 to the release-v6.0 branch. FYI
@felixarntz
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging examples/ai-functions/src/generate-text/anthropic/xhigh-effort.ts
CONFLICT (content): Merge conflict in examples/ai-functions/src/generate-text/anthropic/xhigh-effort.ts
Auto-merging examples/ai-functions/src/stream-text/anthropic/xhigh-effort.ts
CONFLICT (content): Merge conflict in examples/ai-functions/src/stream-text/anthropic/xhigh-effort.ts
Auto-merging packages/amazon-bedrock/src/bedrock-chat-language-model.test.ts
Auto-merging packages/amazon-bedrock/src/bedrock-chat-language-model.ts
error: could not apply ed60b47e6... fix(provider/amazon-bedrock): fix Anthropic reasoning behavior related to Opus 4.7 (#14582)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Felix Arntz <felix.arntz@vercel.com>