Backport: feat(mcp): allow MCP client to use server completions (#16444)
This is an automated backport of #16420 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/docs/03-ai-sdk-core/16-mcp-tools.mdx
Auto-merging content/docs/07-reference/01-ai-sdk-core/23-create-mcp-client.mdx
Auto-merging packages/mcp/src/index.ts
CONFLICT (content): Merge conflict in packages/mcp/src/index.ts
Auto-merging packages/mcp/src/tool/mcp-client.test.ts
Auto-merging packages/mcp/src/tool/mcp-client.ts
Auto-merging packages/mcp/src/tool/mock-mcp-transport.ts
Auto-merging packages/mcp/src/tool/types.ts
error: could not apply 68a739a3e8... feat(mcp): allow MCP client to use server completions (#16420)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>