Backport: docs: remove unnecessary provider imports (#10764)
This is an automated backport of #10763 to the release-v5.0 branch. FYI
@nicoalbanese
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/docs/07-reference/01-ai-sdk-core/02-stream-text.mdx
Auto-merging content/docs/07-reference/01-ai-sdk-core/03-generate-object.mdx
Auto-merging content/docs/07-reference/01-ai-sdk-core/04-stream-object.mdx
Auto-merging content/docs/07-reference/01-ai-sdk-core/05-embed.mdx
Auto-merging content/docs/07-reference/01-ai-sdk-core/06-embed-many.mdx
Auto-merging content/docs/07-reference/01-ai-sdk-core/60-wrap-language-model.mdx
Auto-merging content/docs/07-reference/02-ai-sdk-ui/31-convert-to-model-messages.mdx
CONFLICT (content): Merge conflict in content/docs/07-reference/02-ai-sdk-ui/31-convert-to-model-messages.mdx
error: could not apply d29237155... docs: remove unnecessary provider imports (#10763)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Nico Albanese <49612682+nicoalbanese@users.noreply.github.com>
Co-authored-by: nicoalbanese <gcalbanese96@gmail.com>