Backport: fix(google-vertex): support for eu/us multi region gemini endpoints (#15780)
This is an automated backport of #15777 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
CONFLICT (modify/delete): packages/google-vertex/src/google-vertex-provider-base.test.ts deleted in HEAD and modified in b70f6ec90 (fix(google-vertex): support for eu/us multi region gemini endpoints (#15777)).  Version b70f6ec90 (fix(google-vertex): support for eu/us multi region gemini endpoints (#15777)) of packages/google-vertex/src/google-vertex-provider-base.test.ts left in tree.
CONFLICT (modify/delete): packages/google-vertex/src/google-vertex-provider-base.ts deleted in HEAD and modified in b70f6ec90 (fix(google-vertex): support for eu/us multi region gemini endpoints (#15777)).  Version b70f6ec90 (fix(google-vertex): support for eu/us multi region gemini endpoints (#15777)) of packages/google-vertex/src/google-vertex-provider-base.ts left in tree.
error: could not apply b70f6ec90... fix(google-vertex): support for eu/us multi region gemini endpoints (#15777)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>