Backport: Backport: fix(xai): correctly map the finish-reason (#13924)
This is an automated backport of #13922 to the release-v5.0 branch. FYI
@vercel-ai-sdk[bot]
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging examples/ai-core/src/generate-text/xai-responses-tool-call.ts
CONFLICT (file location): examples/ai-functions/src/stream-text/xai/responses-tool-call.ts added in 5d6154778 (Backport: fix(xai): correctly map the finish-reason (#13922)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/responses-tool-call.ts.
Auto-merging packages/xai/src/responses/xai-responses-language-model.test.ts
CONFLICT (content): Merge conflict in packages/xai/src/responses/xai-responses-language-model.test.ts
Auto-merging packages/xai/src/responses/xai-responses-language-model.ts
CONFLICT (content): Merge conflict in packages/xai/src/responses/xai-responses-language-model.ts
error: could not apply 5d6154778... Backport: fix(xai): correctly map the finish-reason (#13922)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: vercel-ai-sdk[bot] <225926702+vercel-ai-sdk[bot]@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>