Backport: fix(xai): correctly map the finish-reason (#13922)
This is an automated backport of #13909 to the release-v6.0 branch. FYI
@geraint0923
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging packages/xai/src/responses/xai-responses-language-model.test.ts
Auto-merging packages/xai/src/responses/xai-responses-language-model.ts
CONFLICT (content): Merge conflict in packages/xai/src/responses/xai-responses-language-model.ts
error: could not apply 9f20868cc... fix(xai): correctly map the finish-reason (#13909)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Mark <geraint0923@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>