Backport: feat(provider/anthropic): add support for Opus 4.7 and relevant API enhancements (#14530)
This is an automated backport of #14529 to the release-v6.0 branch. FYI
@felixarntz
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging content/docs/02-foundations/02-providers-and-models.mdx
Auto-merging content/providers/01-ai-sdk-providers/05-anthropic.mdx
Auto-merging content/providers/01-ai-sdk-providers/08-amazon-bedrock.mdx
Auto-merging packages/anthropic/src/anthropic-messages-language-model.test.ts
Auto-merging packages/anthropic/src/anthropic-messages-language-model.ts
CONFLICT (content): Merge conflict in packages/anthropic/src/anthropic-messages-language-model.ts
Auto-merging packages/anthropic/src/anthropic-messages-options.ts
error: could not apply 0d8f10713... feat(provider/anthropic): add support for Opus 4.7 and relevant API enhancements (#14529)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Felix Arntz <felix.arntz@vercel.com>