Handle errors in anthropic's web search tool (#15552)
## Background

Currently if web search returns an error, we mishandled it and
lose the tool response when continuing the conversation.

This would result in errors like:
```
Error: messages.1: `web_search` tool use with id `srvtoolu_01DZi3ZdTUsKUj24ZhA1XdSV` was found without a corresponding `web_search_tool_result` block
```

## Summary

web fetch already has handling for this, so reuse that.

## Manual Verification

I verified that trying to continue a conversation with an error failed
on the old version and works with this one.

## Checklist

- [x] All commits are signed (PRs with unsigned commits cannot be
merged)
- [x] Tests have been added / updated (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] A _patch_ changeset for relevant packages has been added (for bug
fixes / features - run `pnpm changeset` in the project root)
- [x] I have reviewed this pull request (self-review)