Backport: feat(provider/mistral): add support for reasoning configuration (mistral-small-latest) (#13690)
This is an automated backport of #13688 to the release-v6.0 branch. FYI
@felixarntz
~~This backport has conflicts that need to be resolved manually.~~

Conflicts resolved, plus implementation updated to only rely on Mistral
`providerOptions`, since the top-level `reasoning` parameter isn't
supported in v6.

### `git cherry-pick` output

```
Auto-merging packages/mistral/src/mistral-chat-language-model.test.ts
CONFLICT (content): Merge conflict in packages/mistral/src/mistral-chat-language-model.test.ts
Auto-merging packages/mistral/src/mistral-chat-language-model.ts
CONFLICT (content): Merge conflict in packages/mistral/src/mistral-chat-language-model.ts
error: could not apply 737b8f4f0... feat(provider/mistral): add support for reasoning configuration (mistral-small-latest) (#13688)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Felix Arntz <felix.arntz@vercel.com>