Backport: fix(openai): change find action type to find_in_page action type (#11106)
This is an automated backport of #10885 to the release-v5.0 branch. FYI
@kkawamu1
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
CONFLICT (modify/delete): examples/next-openai/components/tool/azure-web-search-preview-view.tsx deleted in HEAD and modified in 40dc7fa5e (fix(openai): change find action type to find_in_page action type (#10885)).  Version 40dc7fa5e (fix(openai): change find action type to find_in_page action type (#10885)) of examples/next-openai/components/tool/azure-web-search-preview-view.tsx left in tree.
Auto-merging examples/next-openai/components/tool/openai-web-search-view.tsx
Auto-merging packages/openai/src/responses/__snapshots__/openai-responses-language-model.test.ts.snap
CONFLICT (content): Merge conflict in packages/openai/src/responses/__snapshots__/openai-responses-language-model.test.ts.snap
Auto-merging packages/openai/src/responses/openai-responses-api.ts
Auto-merging packages/openai/src/responses/openai-responses-language-model.ts
Auto-merging packages/openai/src/tool/web-search-preview.ts
CONFLICT (content): Merge conflict in packages/openai/src/tool/web-search-preview.ts
Auto-merging packages/openai/src/tool/web-search.ts
CONFLICT (content): Merge conflict in packages/openai/src/tool/web-search.ts
error: could not apply 40dc7fa5e... fix(openai): change find action type to find_in_page action type (#10885)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: kkawamu1 <58097201+kkawamu1@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <aayushkapoor34@gmail.com>