fix: use appropriate domain for vertex global (#6810)
## Background

Global region for google vertex does not work, this is especially
necessary as some models in their first release are exclusively
available on global region. As of today this is the case for
gemini-2.5-flash-lite.

To test this just set the following env flag
`GOOGLE_VERTEX_LOCATION="global"`

The pattern used in @ai-sdk/google-vertex is 

`https://${region}-aiplatform.googleapis.com/v1/projects/${project}/locations/${region}/publishers/google`

However for global endpoints the domain is different ([see
docs](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/locations#genai-partner-models))
`https://aiplatform.googleapis.com/v1/...`

Resulting in the following error
```js
error: APICallError [AI_APICallError]: Publisher Model `projects/[PROJECT_ID]/locations/us-central1/publishers/google/models/gemini-2.5-flash-lite-preview-06-17` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions
      at <anonymous> ([LOCAL_PATH]/node_modules/@ai-sdk/provider-utils/src/response-handler.ts:59:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async postToApi ([LOCAL_PATH]/node_modules/@ai-sdk/provider-utils/src/post-to-api.ts:111:28)
      at async GoogleGenerativeAILanguageModel.doStream ([LOCAL_PATH]/node_modules/@ai-sdk/google/src/google-generative-ai-language-model.ts:311:50)
      at async fn ([LOCAL_PATH]/node_modules/ai/core/generate-text/stream-text.ts:1032:25)
      at async <anonymous> ([LOCAL_PATH]/node_modules/ai/core/telemetry/record-span.ts:18:22)
      at async _retryWithExponentialBackoff ([LOCAL_PATH]/node_modules/ai/util/retry-with-exponential-backoff.ts:36:12)
      at async streamStep ([LOCAL_PATH]/node_modules/ai/core/generate-text/stream-text.ts:987:15)
      at async fn ([LOCAL_PATH]/node_modules/ai/core/generate-text/stream-text.ts:1466:9)
      at async <anonymous> ([LOCAL_PATH]/node_modules/ai/core/telemetry/record-span.ts:18:22) {
    cause: undefined,
    url: 'https://global-aiplatform.googleapis.com/v1/projects/[PROJECT_ID]/locations/us-central1/publishers/google/models/gemini-2.5-flash-lite-preview-06-17:streamGenerateContent?alt=sse',
```

## Summary

Toggle to use a different pattern in case `region === 'global'`