Backport: feat(ai): add new `isLoopFinished` stop condition helper for unlimited steps (#13966)
This is an automated backport of #13937 to the release-v6.0 branch. FYI
@felixarntz
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging content/docs/03-agents/02-building-agents.mdx
Auto-merging content/docs/07-reference/01-ai-sdk-core/index.mdx
Auto-merging packages/ai/src/generate-text/generate-text.test.ts
CONFLICT (content): Merge conflict in packages/ai/src/generate-text/generate-text.test.ts
Auto-merging packages/ai/src/generate-text/index.ts
Auto-merging packages/ai/src/generate-text/stream-text.test.ts
error: could not apply 5c4d9107b... feat(ai): add new `isLoopFinished` stop condition helper for unlimited steps (#13937)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Felix Arntz <felix.arntz@vercel.com>