Backport: feat (provider/perplexity): add embedding model support (#18069)
This is an automated backport of #17925 to the release-v6.0 branch. FYI
@joshualipman123
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/70-perplexity.mdx
Auto-merging packages/perplexity/src/index.ts
CONFLICT (content): Merge conflict in packages/perplexity/src/index.ts
Auto-merging packages/perplexity/src/perplexity-provider.ts
CONFLICT (content): Merge conflict in packages/perplexity/src/perplexity-provider.ts
error: could not apply 58eee2c258... feat (provider/perplexity): add embedding model support (#17925)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: vercel[bot] <35613825+vercel[bot]@users.noreply.github.com>
Co-authored-by: Vercel <vercel[bot]@users.noreply.github.com>
Co-authored-by: joshualipman123 <joshlipman@g.ucla.edu>