Backport: fix(google): omit passing includeServerSideToolInvocations for Vertex tool_config (#15073)
This is an automated backport of #14767 to the release-v6.0 branch. FYI
@aayush-kapoor
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging packages/google/src/google-generative-ai-language-model.test.ts
Auto-merging packages/google/src/google-generative-ai-language-model.ts
Auto-merging packages/google/src/google-prepare-tools.test.ts
Auto-merging packages/google/src/google-prepare-tools.ts
CONFLICT (content): Merge conflict in packages/google/src/google-prepare-tools.ts
error: could not apply 84f36e07d... fix(google): omit passing includeServerSideToolInvocations for Vertex tool_config (#14767)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Aayush Kapoor <83492835+aayush-kapoor@users.noreply.github.com>