Backport: Backport: feat(provider/cohere): add support for passing images to Cohere models (#14973)
This is an automated backport of #14953 to the release-v5.0 branch. FYI
@github-actions[bot]
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
Auto-merging content/providers/01-ai-sdk-providers/25-cohere.mdx
CONFLICT (file location): examples/ai-functions/src/generate-text/cohere/image.ts added in 563e9dd1f (Backport: feat(provider/cohere): add support for passing images to Cohere models (#14953)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/image.ts.
CONFLICT (file location): examples/ai-functions/src/stream-text/cohere/image.ts added in 563e9dd1f (Backport: feat(provider/cohere): add support for passing images to Cohere models (#14953)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/image.ts.
Auto-merging packages/cohere/src/cohere-chat-language-model.ts
Auto-merging packages/cohere/src/cohere-chat-options.ts
CONFLICT (content): Merge conflict in packages/cohere/src/cohere-chat-options.ts
Auto-merging packages/cohere/src/convert-to-cohere-chat-prompt.ts
CONFLICT (content): Merge conflict in packages/cohere/src/convert-to-cohere-chat-prompt.ts
error: could not apply 563e9dd1f... Backport: feat(provider/cohere): add support for passing images to Cohere models (#14953)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>