Backport: docs: update cookbook to use gateway (#10593)
This is an automated backport of #10590 to the release-v5.0 branch. FYI
@nicoalbanese
This backport has conflicts that need to be resolved manually.

### `git cherry-pick` output

```
Auto-merging content/cookbook/01-next/122-caching-middleware.mdx
Auto-merging content/cookbook/05-node/56-web-search-agent.mdx
CONFLICT (content): Merge conflict in content/cookbook/05-node/56-web-search-agent.mdx
error: could not apply 4ce81f392... docs: update cookbook to use gateway (#10590)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: Nico Albanese <49612682+nicoalbanese@users.noreply.github.com>
Co-authored-by: nicoalbanese <gcalbanese96@gmail.com>