Backport: Backport: fix(provider/google): support `functionCall.id` when returned by Gemini API and provide matching `functionResponse.id` (#15323)
This is an automated backport of #15318 to the release-v5.0 branch. FYI
@github-actions[bot]
~~This backport has conflicts that need to be resolved manually.~~
Conflicts resolved.

### `git cherry-pick` output

```
CONFLICT (file location): examples/ai-functions/src/generate-text/google/function-call-id.ts added in 3ca0daa8e (Backport: fix(provider/google): support `functionCall.id` when returned by Gemini API and provide matching `functionResponse.id` (#15318)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/generate-text/function-call-id.ts.
CONFLICT (file location): examples/ai-functions/src/stream-text/google/function-call-id.ts added in 3ca0daa8e (Backport: fix(provider/google): support `functionCall.id` when returned by Gemini API and provide matching `functionResponse.id` (#15318)) inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to examples/ai-core/src/stream-text/function-call-id.ts.
Auto-merging packages/google/src/convert-to-google-generative-ai-messages.test.ts
CONFLICT (content): Merge conflict in packages/google/src/convert-to-google-generative-ai-messages.test.ts
Auto-merging packages/google/src/convert-to-google-generative-ai-messages.ts
CONFLICT (content): Merge conflict in packages/google/src/convert-to-google-generative-ai-messages.ts
Auto-merging packages/google/src/google-generative-ai-language-model.ts
CONFLICT (content): Merge conflict in packages/google/src/google-generative-ai-language-model.ts
Auto-merging packages/google/src/google-generative-ai-prompt.ts
error: could not apply 3ca0daa8e... Backport: fix(provider/google): support `functionCall.id` when returned by Gemini API and provide matching `functionResponse.id` (#15318)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
```

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Felix Arntz <felix.arntz@vercel.com>